sources:
  - name: superstore
    description: Data from Superstore dataset
    database: SURFALYTICS_DW_AIZHAN
    schema: raw
    tables:
      - name: orders
        description: Raw orders data
      - name: people
        description: Raw data for regional managers
      - name: returns
        description: Raw data for returned orders
